runtime: python311
instance_class: F2
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --timeout 300 --bind :$PORT main:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 5
  min_idle_instances: 0
  max_idle_instances: 1

env_variables:
  PROJECT_ID: "zensai-poc"
  PYTHONUNBUFFERED: "1"

handlers:
  - url: /.*
    script: auto
    secure: always
